name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Backend
      run: dotnet build --no-restore
    # Nơi đây có thể thêm lệnh dotnet test nếu project của bạn có viết Unit Test
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install dependencies
      working-directory: ./Frontend
      run: npm install
    - name: Build Frontend
      working-directory: ./Frontend
      run: npm run build
